default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  pool: 5

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test